### ISSUE TITLE
[mock-udp] Unable to import when using CommonJS

### ISSUE THREAD

**Issue by smnodame** [ffflorian/node-packages#265]
I got this error from the latest version 1.4.1, I see you have cjs amd mjs folder which handle differrently for commonjs and es module
but the bundle file in cjs still using the import  syntax which I suspect that it's wrong. the old version works (1.0.2) works fine for me since it compiles to use require syntax for import

```
/home/smnodame/MyProject/screenos-supervisor/node_modules/ntpclient/dist/cjs/index.js:2
import dgram from 'node:dgram';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .js] (/home/smnodame/MyProject/screenos-supervisor/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/smnodame/MyProject/screenos-supervisor/src/modules/datetime/dateTimeManager.ts:2:1)
[nodemon] app crashed - waiting for file changes before starting..
```

**Comment by ffflorian** [comment]
@smnodame Thanks for the report, I'll check it as soon as possible.

**Comment by iKK001** [comment]
I have the same problem:  library does not work for my nodeJS applicaton (typescript) - any solution to this ??

**Comment by ffflorian** [comment]
Hi, since I am not publishing CommonJS modules anymore, I am going to close this issue.
